# src/audit/stages/stage_7_anhang.py
import logging
import json
import asyncio
from typing import Dict, Any, List
from google.cloud.exceptions import NotFound

from src.config import AppConfig
from src.clients.gcs_client import GcsClient
from src.clients.ai_client import AiClient

class Chapter7Runner:
    """
    Handles generating the appendix for Chapter 7.
    - 7.1 is generated deterministically by listing GCS files.
    - 7.2 is generated by an AI summarizing findings from Chapters 3 & 5.
    """
    STAGE_NAME = "Chapter-7"

    def __init__(self, config: AppConfig, gcs_client: GcsClient, ai_client: AiClient):
        self.config = config
        self.gcs_client = gcs_client
        self.ai_client = ai_client
        logging.info(f"Initialized runner for stage: {self.STAGE_NAME}")

    def _load_asset_text(self, path: str) -> str:
        with open(path, 'r', encoding='utf-8') as f: return f.read()

    def _load_asset_json(self, path: str) -> dict:
        with open(path, 'r', encoding='utf-8') as f: return json.load(f)

    async def _generate_referenzdokumente_table(self) -> Dict[str, Any]:
        logging.info("Generating subchapter 7.1 (Referenzdokumente) from GCS file list.")
        try:
            source_files = self.gcs_client.list_source_files()
            rows = []
            for i, blob in enumerate(source_files):
                rows.append({
                    "Nr.": f"A.{i}",
                    "Kurzbezeichnung": blob.name.split('/')[-1],
                    "Dateiname / Verweis": blob.name,
                    "Version, Datum": blob.updated.strftime("%Y-%m-%d") if blob.updated else "N/A",
                    "Relevante Änderungen": "Initial eingereicht für Audit."
                })
            return {"referenzdokumente": {"rows": rows}}
        except Exception as e:
            logging.error(f"Failed to generate Referenzdokumente table: {e}", exc_info=True)
            return {"referenzdokumente": {"rows": []}}

    async def _generate_abweichungen_table(self) -> Dict[str, Any]:
        """Uses AI to summarize deviations from Chapter 3 and 5 results."""
        logging.info("Generating subchapter 7.2 (Abweichungen und Empfehlungen)...")
        raw_deviations = []

        # 1. Load and parse Chapter 3 results
        try:
            ch3_results = self.gcs_client.read_json(f"{self.config.output_prefix}results/Chapter-3.json")
            for subchapter, result in ch3_results.items():
                if result and 'findingText' in result:
                    finding_text = result['findingText'].lower()
                    if "keine abweichung" not in finding_text and "erfüllt" not in finding_text:
                        raw_deviations.append(f"- Finding in Chapter 3 ({subchapter}): {result['findingText']}")
        except NotFound:
            logging.warning("Chapter 3 results not found. Skipping for deviation summary.")
        except Exception as e:
            logging.error(f"Could not parse Chapter 3 results: {e}")

        # 2. Load and parse Chapter 5 results
        try:
            ch5_results = self.gcs_client.read_json(f"{self.config.output_prefix}results/Chapter-5.json")
            # Parse explicit deviations from control verifications (5.5.2)
            pruefungen = ch5_results.get("verifikationDesITGrundschutzChecks", {}).get("bausteinPruefungen", [])
            for pruefung in pruefungen:
                for anforderung in pruefung.get("anforderungen", []):
                    if anforderung.get("bewertung") in ["Teilweise", "Mangelhaft"] or anforderung.get("abweichungen") not in [None, "", "Keine."]:
                        raw_deviations.append(f"- Control {anforderung['nummer']}: {anforderung['anforderung']}. Finding: {anforderung['auditfeststellung']}. Deviation: {anforderung['abweichungen']}")
        except NotFound:
            logging.warning("Chapter 5 results not found. Skipping for deviation summary.")
        except Exception as e:
            logging.error(f"Could not parse Chapter 5 results: {e}")

        # 3. If deviations were found, call AI to summarize them
        if not raw_deviations:
            logging.info("No deviations found in Chapters 3 or 5. Skipping AI call for 7.2.")
            return {"abweichungenUndEmpfehlungen": {"rows": []}}

        prompt_template = self._load_asset_text("assets/prompts/stage_7_2_abweichungen.txt")
        schema = self._load_asset_json("assets/schemas/stage_7_2_abweichungen_schema.json")
        prompt = prompt_template.format(raw_deviations="\n".join(raw_deviations))
        
        try:
            generated_data = await self.ai_client.generate_json_response(prompt, schema)
            return {"abweichungenUndEmpfehlungen": generated_data}
        except Exception as e:
            logging.error(f"Failed to generate Abweichungen table via AI: {e}", exc_info=True)
            return {"abweichungenUndEmpfehlungen": {"rows": []}}

    async def run(self) -> dict:
        logging.info(f"Executing stage: {self.STAGE_NAME}")
        tasks = [self._generate_referenzdokumente_table(), self._generate_abweichungen_table()]
        results_list = await asyncio.gather(*tasks)
        aggregated_results = {}
        for res_dict in results_list:
            aggregated_results.update(res_dict)
        logging.info(f"Successfully aggregated results for all of stage {self.STAGE_NAME}")
        return aggregated_results